# Generated by Django 5.2.16 on 2026-07-28 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.SlugField(unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(default='general', max_length=32)),
                ('priority', models.CharField(default='normal', max_length=16)),
                ('unread_for_staff', models.PositiveIntegerField(default=0)),
                ('unread_for_admin', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='portal.portalunit')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('audience', models.CharField(blank=True, max_length=255)),
                ('channels', models.JSONField(default=list)),
                ('status', models.CharField(default='Draft', max_length=32)),
                ('style', models.CharField(default='info', max_length=32)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='portal.portalunit')),
            ],
            options={
                'ordering': ['-posted_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PortalIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('incident_type', models.CharField(max_length=64)),
                ('severity', models.CharField(max_length=32)),
                ('summary', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('staff_reported', models.CharField(blank=True, default='Staff', max_length=120)),
                ('parent_notified', models.BooleanField(default=False)),
                ('parent_notified_time', models.TimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('follow_up', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='portal.portalchild')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='portal.portalunit')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='PortalNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('template_id', models.CharField(blank=True, max_length=64)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(default='Draft', max_length=32)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('recipients_label', models.CharField(blank=True, max_length=64)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='portal.portalunit')),
            ],
            options={
                'ordering': ['-sent_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SupportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='portal/support/%Y/%m/')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='portal.supportmessage')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=32, unique=True)),
                ('from_area', models.CharField(max_length=16)),
                ('from_name', models.CharField(max_length=120)),
                ('from_detail', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(default='other', max_length=32)),
                ('status', models.CharField(default='Open', max_length=32)),
                ('preview_family_slug', models.CharField(blank=True, max_length=64)),
                ('unread_for_admin', models.PositiveIntegerField(default=0)),
                ('unread_for_user', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.portalfamily')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='portal.portalunit')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='portal.supportticket'),
        ),
        migrations.CreateModel(
            name='TeamMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='portal.messagethread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
