# Generated by Django 5.2.16 on 2026-07-28 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_supportmessage_messagethread_portalannouncement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(blank=True, max_length=120)),
                ('date', models.DateField()),
                ('entry_type', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='portal.portalfamily')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalParentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('autopay_enabled', models.BooleanField(default=False)),
                ('autopay_day', models.CharField(blank=True, max_length=64)),
                ('email_receipts', models.BooleanField(default=True)),
                ('email_reminders', models.BooleanField(default=True)),
                ('sms_reminders', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_account', to='portal.portalfamily')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_parent_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['family__name'],
            },
        ),
        migrations.CreateModel(
            name='PortalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(blank=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_charged', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('method_label', models.CharField(blank=True, max_length=120)),
                ('payment_kind', models.CharField(default='balance', max_length=32)),
                ('dropin_child', models.CharField(blank=True, max_length=120)),
                ('dropin_program', models.CharField(blank=True, max_length=120)),
                ('dropin_location', models.CharField(blank=True, max_length=120)),
                ('dropin_date', models.CharField(blank=True, max_length=64)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='portal.portalfamily')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
