# Generated by Django 5.2.16 on 2026-07-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_parent_accounts_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalparentaccount',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='portal/parent-photos/%Y/%m/'),
        ),
    ]
