# Generated by Django 5.2.16 on 2026-07-29 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_parent_profile_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalBillingDefaultRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=64, unique=True)),
                ('can_add_charge', models.BooleanField(default=True)),
                ('can_delete_charge', models.BooleanField(default=False)),
                ('can_add_credit', models.BooleanField(default=False)),
                ('can_edit_family_plans', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['role_name'],
            },
        ),
        migrations.CreateModel(
            name='PortalCheckInSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='PortalFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('amount', models.CharField(blank=True, max_length=32)),
                ('display', models.CharField(blank=True, max_length=64)),
                ('frequency', models.CharField(blank=True, max_length=64)),
                ('period', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortalOrgPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, default='1.0', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Portal org policies',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PortalPaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('interval', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortalProcessingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('flat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortalScholarshipFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortalStaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortalTaxStatementSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_zero_balance', models.BooleanField(default=True)),
                ('parents_enabled', models.BooleanField(default=True)),
                ('staff_can_view', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AddField(
            model_name='portalagencyprofile',
            name='daily_copay_rates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='portalagencyprofile',
            name='rate_tier_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='portalagencyprofile',
            name='use_variable_rates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portalannouncement',
            name='body_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portalnewsletter',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portalprogram',
            name='age_max',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='portalprogram',
            name='age_min',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='portalprogram',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalprogram',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portalprogram',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalprogram',
            name='program_type',
            field=models.CharField(blank=True, default='after_school', max_length=32),
        ),
        migrations.AddField(
            model_name='portalprogram',
            name='reg_close',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalprogram',
            name='reg_open',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalprogram',
            name='season',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='portalprogram',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalprogram',
            name='status_label',
            field=models.CharField(blank=True, default='Active', max_length=64),
        ),
        migrations.AddField(
            model_name='portalstaffaccount',
            name='accessible_units',
            field=models.ManyToManyField(blank=True, related_name='staff_with_access', to='portal.portalunit'),
        ),
        migrations.AddField(
            model_name='portalstaffaccount',
            name='all_units_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portalstaffaccount',
            name='can_edit_family_plans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portalstaffaccount',
            name='charge_type_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='portalunit',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='portalunit',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalunit',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='portalunit',
            name='manager_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='portalunit',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='portalunit',
            name='program_type',
            field=models.CharField(blank=True, default='after_school', max_length=32),
        ),
        migrations.CreateModel(
            name='PortalAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('default_weekly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remittance_schedule', models.CharField(blank=True, default='Monthly (1st business day)', max_length=64)),
                ('rate_tiers', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('units', models.ManyToManyField(blank=True, related_name='agencies', to='portal.portalunit')),
            ],
            options={
                'verbose_name_plural': 'Portal agencies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='portalagencyprofile',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_profiles', to='portal.portalagency'),
        ),
        migrations.CreateModel(
            name='PortalScholarshipAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=32)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='portal.portalchild')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='portal.portalscholarshipfund')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PortalWaivedAbsenceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_slug', models.SlugField()),
                ('child_name', models.CharField(max_length=120)),
                ('week_label', models.CharField(max_length=64)),
                ('charge_description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-waived_at'],
                'unique_together': {('family_slug', 'child_name', 'week_label', 'charge_description')},
            },
        ),
        migrations.CreateModel(
            name='PortalPolicySignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed')], default='pending', max_length=16)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_requests', to='portal.portalchild')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_requests', to='portal.portalfamily')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='portal.portalorgpolicy')),
            ],
            options={
                'ordering': ['-notified_at'],
                'unique_together': {('child', 'policy')},
            },
        ),
    ]
