# Generated by Django 5.2.17 on 2026-09-05 18:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_payment_stripe_settlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalDropOffSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_cutoff_time', models.TimeField(default=datetime.time(10, 0))),
                ('book_ahead_days', models.PositiveSmallIntegerField(default=14)),
                ('booking_open', models.BooleanField(default=True)),
                ('parent_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Drop-off settings',
                'verbose_name_plural': 'Drop-off settings',
            },
        ),
        migrations.AddField(
            model_name='portalchild',
            name='is_drop_off',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PortalDropOffSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')])),
                ('start_time', models.TimeField()),
                ('label', models.CharField(max_length=120)),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('school_note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_off_slots', to='portal.portalunit')),
            ],
            options={
                'ordering': ['unit__name', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='PortalDropOffBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('slot_label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('requested', 'Requested — waiting for payment'), ('paid', 'Paid — pick up'), ('cancelled', 'Cancelled')], default='requested', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('parent_notified_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_off_bookings', to='portal.portalchild')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_off_bookings', to='portal.portalfamily')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_off_bookings', to='portal.portalpayment')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_off_bookings', to='portal.portalunit')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='portal.portaldropoffslot')),
            ],
            options={
                'ordering': ['care_date', 'start_time', 'child__name'],
            },
        ),
    ]
