# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0017_drop_off_program"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalEmailTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.SlugField(
                        choices=[
                            ("staff_welcome", "Staff / admin welcome"),
                            ("charge_notice", "Charge posted"),
                            ("first_day_reminder", "First-day payment reminder"),
                        ],
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("is_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
