# Generated by Django 5.2.17 on 2026-09-09 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_email_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalagencyprofile',
            name='daily_agency_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='portalagencyprofile',
            name='daily_copay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='portalagencyprofile',
            name='weekly_agency_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portalagencyprofile',
            name='weekly_copay_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='portalagencyprofile',
            name='auth_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='PortalAgencyContractWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('agency_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('agency_overridden', models.BooleanField(default=False)),
                ('parent_overridden', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('parent_posted', models.BooleanField(default=False)),
                ('parent_posted_on', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_weeks', to='portal.portalagencyprofile')),
            ],
            options={
                'ordering': ['week_start'],
                'unique_together': {('profile', 'week_start')},
            },
        ),
    ]
