# Generated by Django 5.2.17 on 2026-09-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_agency_contract_weeks'),
        ('portal', '0019_child_unit'),
    ]

    operations = [
    ]
