# Generated by Django 5.2.17 on 2026-09-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_ledger_fee_amount'),
        ('portal', '0023_parent_email_ledger'),
    ]

    operations = [
    ]
