# Generated by Django 5.2.17 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0024_merge_ledger_fee_and_parent_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalProgramCalendar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("program_start", models.DateField(blank=True, null=True)),
                ("days_off", models.JSONField(blank=True, default=list)),
                ("half_days", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Program calendar",
                "verbose_name_plural": "Program calendar",
            },
        ),
        migrations.AddField(
            model_name="portalagencycontractweek",
            name="agency_included",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="portalagencycontractweek",
            name="agency_included_overridden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="portalagencycontractweek",
            name="parent_included",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="portalagencycontractweek",
            name="parent_included_overridden",
            field=models.BooleanField(default=False),
        ),
    ]
