# Generated by Django 5.2.16 on 2026-07-26 19:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DropInDayCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('after_school', 'After-school drop-in'), ('summer_camp', 'Summer camp drop-in')], max_length=20)),
                ('location', models.CharField(choices=[('school_18', 'School 18 — Paterson'), ('school_26', 'School 26 — Paterson'), ('dale_ave', 'Dale Ave — Paterson (bus to School 18)'), ('caldwell', 'Caldwell University')], max_length=20)),
                ('date', models.DateField()),
                ('max_slots', models.PositiveSmallIntegerField(help_text='Maximum drop-in spots available this day at this location.')),
            ],
            options={
                'verbose_name_plural': 'Drop-in day capacities',
                'ordering': ['date', 'program', 'location'],
                'unique_together': {('program', 'location', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DropInFamilyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_name', models.CharField(max_length=120)),
                ('primary_email', models.EmailField(max_length=254)),
                ('home_address', models.TextField()),
                ('primary_first_name', models.CharField(max_length=80)),
                ('primary_last_name', models.CharField(max_length=80)),
                ('primary_phone', models.CharField(max_length=30)),
                ('secondary_first_name', models.CharField(blank=True, max_length=80)),
                ('secondary_last_name', models.CharField(blank=True, max_length=80)),
                ('secondary_phone', models.CharField(blank=True, max_length=30)),
                ('allergies', models.TextField(blank=True)),
                ('no_known_allergies', models.BooleanField(default=False)),
                ('requires_allergy_plan', models.BooleanField(default=False)),
                ('requires_asthma_plan', models.BooleanField(default=False)),
                ('requires_epipen_plan', models.BooleanField(default=False)),
                ('has_medical_condition', models.CharField(blank=True, max_length=3)),
                ('medical_condition_explain', models.TextField(blank=True)),
                ('health_statement', models.CharField(blank=True, max_length=30)),
                ('doctor_name', models.CharField(blank=True, max_length=120)),
                ('doctor_phone', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dropin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='DropInEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=30)),
                ('relationship', models.CharField(max_length=80)),
                ('authorized_pickup', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='dropin.dropinfamilyprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DropInChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('grade', models.CharField(choices=[('pre_k', 'Pre-K'), ('kindergarten', 'Kindergarten'), ('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th')], max_length=20)),
                ('school', models.CharField(max_length=120)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dropin.dropinfamilyprofile')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='DropInBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('program', models.CharField(choices=[('after_school', 'After-school drop-in'), ('summer_camp', 'Summer camp drop-in')], max_length=20)),
                ('location', models.CharField(choices=[('school_18', 'School 18 — Paterson'), ('school_26', 'School 26 — Paterson'), ('dale_ave', 'Dale Ave — Paterson (bus to School 18)'), ('caldwell', 'Caldwell University')], max_length=20)),
                ('date', models.DateField()),
                ('amount_cents', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='dropin.dropinchild')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='dropin.dropinfamilyprofile')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('child', 'program', 'location', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DropInPolicySignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_slug', models.CharField(max_length=80)),
                ('policy_title', models.CharField(max_length=200)),
                ('signature_name', models.CharField(max_length=120)),
                ('signed_date', models.DateField()),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_signatures', to='dropin.dropinfamilyprofile')),
            ],
            options={
                'unique_together': {('profile', 'policy_slug')},
            },
        ),
    ]
