# Generated by Django 5.2.16 on 2026-07-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropinfamilyprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
