# Generated by Django 5.2.16 on 2026-07-26 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropin', '0002_dropinfamilyprofile_approved_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropInWaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('after_school', 'After-school drop-in'), ('summer_camp', 'Summer camp drop-in')], max_length=20)),
                ('location', models.CharField(choices=[('school_18', 'School 18 — Paterson'), ('school_26', 'School 26 — Paterson'), ('dale_ave', 'Dale Ave — Paterson (bus to School 18)'), ('caldwell', 'Caldwell University')], max_length=20)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('offered', 'Offered spot'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='dropin.dropinchild')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='dropin.dropinfamilyprofile')),
            ],
            options={
                'ordering': ['date', 'program', 'location', 'created_at'],
                'unique_together': {('child', 'program', 'location', 'date')},
            },
        ),
    ]
