# Generated by Django 5.2.16 on 2026-07-26 06:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('family_name', models.CharField(max_length=120)),
                ('primary_email', models.EmailField(max_length=254)),
                ('home_address', models.TextField()),
                ('primary_first_name', models.CharField(max_length=80)),
                ('primary_last_name', models.CharField(max_length=80)),
                ('primary_gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=10)),
                ('primary_language', models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('other', 'Other')], max_length=20)),
                ('primary_language_other', models.CharField(blank=True, max_length=80)),
                ('primary_relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=20)),
                ('primary_relationship_other', models.CharField(blank=True, max_length=80)),
                ('primary_phone', models.CharField(max_length=30)),
                ('primary_phone_type', models.CharField(choices=[('cell', 'Cell Phone'), ('home', 'Home Phone')], max_length=10)),
                ('primary_text_subscription', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('primary_email_subscription', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('primary_email_address', models.EmailField(max_length=254)),
                ('primary_authorized_pickup', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('secondary_first_name', models.CharField(blank=True, max_length=80)),
                ('secondary_last_name', models.CharField(blank=True, max_length=80)),
                ('secondary_gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=10)),
                ('secondary_language', models.CharField(blank=True, choices=[('english', 'English'), ('spanish', 'Spanish'), ('other', 'Other')], max_length=20)),
                ('secondary_language_other', models.CharField(blank=True, max_length=80)),
                ('secondary_relationship', models.CharField(blank=True, choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=20)),
                ('secondary_relationship_other', models.CharField(blank=True, max_length=80)),
                ('secondary_phone', models.CharField(blank=True, max_length=30)),
                ('secondary_phone_type', models.CharField(blank=True, choices=[('cell', 'Cell Phone'), ('home', 'Home Phone')], max_length=10)),
                ('secondary_text_subscription', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('secondary_email_subscription', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('secondary_email_address', models.EmailField(blank=True, max_length=254)),
                ('secondary_authorized_pickup', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('student_first_name', models.CharField(max_length=80)),
                ('student_last_name', models.CharField(max_length=80)),
                ('student_gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=10)),
                ('student_dob', models.DateField()),
                ('student_language', models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('other', 'Other')], max_length=20)),
                ('student_language_other', models.CharField(blank=True, max_length=80)),
                ('student_ethnicity', models.CharField(choices=[('hispanic', 'Hispanic/Latino'), ('non_hispanic', 'Non-Hispanic/Latino'), ('unknown', 'Unknown')], max_length=20)),
                ('student_race', models.CharField(choices=[('black', 'Black or African American'), ('white', 'White'), ('native_hawaiian', 'Native Hawaiian'), ('asian', 'Asian'), ('american_indian', 'American Indian'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=30)),
                ('student_race_other', models.CharField(blank=True, max_length=80)),
                ('student_grade', models.CharField(choices=[('pre_k', 'Pre-K'), ('kindergarten', 'Kindergarten'), ('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th')], max_length=20)),
                ('student_school', models.CharField(max_length=120)),
                ('program_location', models.CharField(choices=[('school_18', 'School 18'), ('school_26', 'School 26')], max_length=20)),
                ('needs_dale_ave_bus', models.BooleanField(default=False)),
                ('doctor_name', models.CharField(blank=True, max_length=120)),
                ('doctor_phone', models.CharField(blank=True, max_length=30)),
                ('insurance_provider', models.CharField(blank=True, max_length=120)),
                ('insurance_policy_group', models.CharField(blank=True, max_length=120)),
                ('insurance_member_id', models.CharField(blank=True, max_length=120)),
                ('no_insurance', models.BooleanField(default=False)),
                ('allergies', models.TextField(blank=True)),
                ('no_known_allergies', models.BooleanField(default=False)),
                ('requires_allergy_plan', models.BooleanField(default=False)),
                ('requires_asthma_plan', models.BooleanField(default=False)),
                ('requires_epipen_plan', models.BooleanField(default=False)),
                ('has_disability', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('has_special_needs', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('requires_medication', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('has_medical_condition', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('medical_condition_explain', models.TextField(blank=True)),
                ('health_statement', models.CharField(choices=[('good_health', 'My child is in good health and can participate in normal activities.'), ('needs_accommodation', 'My child can participate but has conditions requiring special accommodation.')], max_length=30)),
                ('membership_fee_agreed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('payment_method', models.CharField(choices=[('private_pay', 'Private Pay (card)'), ('4cs', '4Cs'), ('other', 'Other')], max_length=20)),
                ('payment_method_other', models.CharField(blank=True, max_length=120)),
                ('late_fees_understood', models.BooleanField(default=False)),
                ('payment_plan', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('payment_plan_signature', models.CharField(max_length=120)),
                ('payment_plan_signed_date', models.DateField()),
                ('four_cs_signature', models.CharField(blank=True, max_length=120)),
                ('four_cs_signed_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=30)),
                ('relationship', models.CharField(max_length=80)),
                ('authorized_pickup', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='enrollment.enrollmentapplication')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PolicySignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_slug', models.CharField(max_length=80)),
                ('policy_title', models.CharField(max_length=200)),
                ('signature_name', models.CharField(max_length=120)),
                ('signed_date', models.DateField()),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_signatures', to='enrollment.enrollmentapplication')),
            ],
            options={
                'unique_together': {('application', 'policy_slug')},
            },
        ),
    ]
