# Generated by Django 5.2.16 on 2026-07-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentapplication',
            name='program',
            field=models.CharField(choices=[('after_school', 'After-school program'), ('summer_camp', 'Summer camp')], default='after_school', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='program_location',
            field=models.CharField(choices=[('school_18', 'School 18 — Paterson'), ('school_26', 'School 26 — Paterson'), ('caldwell', 'Caldwell University')], max_length=20),
        ),
    ]
