# Generated by Django 5.2.16 on 2026-07-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_add_program_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentapplication',
            name='child_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='family_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='program_location',
            field=models.CharField(choices=[('school_18', 'School 18 — Paterson'), ('school_26', 'School 26 — Paterson'), ('dale_ave', 'Dale Ave — Paterson (bus to School 18)'), ('caldwell', 'Caldwell University')], max_length=20),
        ),
    ]
