# Generated by Django 5.2.16 on 2026-07-28 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_enrollmentapplication_child_number_and_more'),
        ('portal', '0003_parent_accounts_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentapplication',
            name='portal_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_applications', to='portal.portalfamily'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under review'), ('approved', 'Approved'), ('pending_documents', 'Pending documents'), ('enrolled', 'Enrolled'), ('declined', 'Declined')], default='under_review', max_length=32),
        ),
    ]
