# Generated by Django 5.2.16 on 2026-07-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_application_portal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentapplication',
            name='internal_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='staff_message',
            field=models.TextField(blank=True, help_text='Message shown to the parent when changes are requested or an application is declined.'),
        ),
    ]
